
openapi: '3.0.2'
info:
  title: API FastAPI
  version: '1.0'
servers:
  - url: https://api.server.test/v1

components:
  schemas:
    devices:
      type: array
      items:
        $ref: '#/components/schemas/device'
    device:
      type: object
      required:
        - "deviceName"
        - "deviceType"
      properties:
        deviceId:
          type: "string"
          description: "Unique id of device"
        deviceName:
          type: "string"
          description: "Name of device"
        deviceType:
          type: "string"
          description: "Type of the device"
          enum: ["co2", "pir"]
    
    
paths:
  /devices:
    get:
      description: 'get the list of devices'
      responses:
        '200':
          description: 'List of devices'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices'
      x-amazon-apigateway-integration:
        credentials:
          Fn::Sub: ${ApiRole.Arn}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDevices.Arn}/invocations
        httpMethod: POST
        timeoutInMillis: 3000
        type: "aws_proxy"
  